# Generated by Django 3.1.4 on 2021-01-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_de_dossier', models.CharField(max_length=20, null=True)),
                ('n_de_contrat', models.CharField(max_length=20, null=True)),
                ('raison_sociale', models.CharField(max_length=100, null=True)),
                ('siren', models.CharField(max_length=20, null=True)),
                ('adresse', models.CharField(max_length=200, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
