# Generated by Django 3.1.4 on 2021-01-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=100, null=True)),
                ('siren', models.IntegerField(max_length=20, null=True)),
                ('adresse', models.CharField(max_length=200, null=True)),
                ('code_postal', models.CharField(max_length=20, null=True)),
                ('ville', models.CharField(max_length=20, null=True)),
                ('RCS', models.CharField(max_length=20, null=True)),
                ('lieu_d_installation', models.CharField(max_length=20, null=True)),
                ('telephone_fixe', models.CharField(max_length=20, null=True)),
                ('telephone_portable', models.CharField(max_length=20, null=True)),
                ('IBAN', models.CharField(max_length=50, null=True)),
                ('BIC', models.CharField(max_length=20, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborateurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_collaborateur', models.CharField(max_length=20, null=True)),
                ('numero_collaborateur', models.IntegerField(max_length=20, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dossiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_de_contrat', models.CharField(max_length=20, null=True)),
                ('montant', models.IntegerField(max_length=9, null=True)),
                ('type_equipement', models.CharField(choices=[('Matériel informatique', 'Matériel informatique'), ('Equipement industriel', 'Equipement industriel'), ('Logiciels', 'Logiciels'), ('Equipement médical', 'Equipement médical'), ('Autre équipement', 'Autre équipement')], max_length=50, null=True)),
                ('duree', models.CharField(choices=[('24 mois', '24 mois'), ('36 mois', '36 mois'), ('48 mois', '48 mois'), ('60 mois', '60 mois'), ('72 mois', '72 mois'), ('84 mois', '84 mois')], max_length=20, null=True)),
                ('periodicite', models.CharField(choices=[('mensuel', 'mensuel'), ('trimestriel', 'trimestriel')], max_length=20, null=True)),
                ('nom_fournisseur', models.CharField(max_length=100, null=True)),
                ('siren_fournisseur', models.IntegerField(max_length=20, null=True)),
                ('loyer', models.IntegerField(max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Dossier',
        ),
    ]
