# Generated by Django 3.1.4 on 2021-01-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_auto_20210108_2005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Collaborateurs',
            new_name='Collaborateur',
        ),
        migrations.RenameModel(
            old_name='Dossiers',
            new_name='Dossier',
        ),
    ]
