# Generated by Django 3.1.4 on 2021-01-08 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0004_auto_20210108_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP.client'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='collaborateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP.collaborateur'),
        ),
    ]
